#!name= host
#!desc= host

[Rule]
DOMAIN,abplatform.yumchina.com,REJECT
[MITM]
hostname = api.zhihu.com,
www.zhihu.com,
api-access.pangolin-sdk-toutiao.com,
api-access.pangolin-sdk-toutiao-b.com,
*.pangolin-sdk-toutiao.*,
*.pstatp.com,*.pstatp.com.*,
*.pglstatp-toutiao.com.*,
*.pglstatp-toutiao.com,
gurd.snssdk.com,
gurd.snssdk.com.*,
*default.ixigua.com,
broadcast.chat.bilibili.com,
api.biibili.com,
webboot.zhangyue.com,
saad.ms.zhangyue.net,
bookbk.img.ireader.com,
